# Generated by Django 5.2.5 on 2025-08-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdMast',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StckMain',
            fields=[
                ('transid', models.AutoField(primary_key=True, serialize=False)),
                ('transdate', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StckDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.prodmast')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stckmain')),
            ],
        ),
    ]
