# Generated by Django 5.2.5 on 2025-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodmast',
            old_name='prodid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='stckdetail',
            old_name='prod',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stckdetail',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stckdetail',
            old_name='trans',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stckmain',
            old_name='transdate',
            new_name='stock_date',
        ),
        migrations.RenameField(
            model_name='stckmain',
            old_name='transid',
            new_name='stock_id',
        ),
        migrations.RemoveField(
            model_name='prodmast',
            name='prodname',
        ),
        migrations.RemoveField(
            model_name='stckdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stckmain',
            name='remarks',
        ),
        migrations.AddField(
            model_name='prodmast',
            name='category',
            field=models.CharField(default='Misc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodmast',
            name='product_name',
            field=models.CharField(default='Misc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stckdetail',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='stckmain',
            name='transaction_type',
            field=models.CharField(default='IN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodmast',
            name='price',
            field=models.FloatField(),
        ),
    ]
