# Generated by Django 5.2.5 on 2025-08-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_prodid_prodmast_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stckmain',
            old_name='stock_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='prodmast',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prodmast',
            name='price',
        ),
        migrations.AlterField(
            model_name='prodmast',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stckdetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stckmain',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
    ]
