# Generated by Django 5.2.5 on 2025-08-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_stock_date_stckmain_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='stckdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stckdetail',
            name='stock',
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('stock_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockmain')),
            ],
        ),
        migrations.DeleteModel(
            name='ProdMast',
        ),
        migrations.DeleteModel(
            name='StckDetail',
        ),
        migrations.DeleteModel(
            name='StckMain',
        ),
    ]
